# Generated by Django 2.2.3 on 2019-11-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('played_datetime', models.DateTimeField()),
                ('time', models.DurationField()),
                ('number_of_hints', models.IntegerField()),
            ],
        ),
    ]
