# Generated by Django 2.2.7 on 2019-11-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escaperoom',
            old_name='time',
            new_name='duration_time',
        ),
    ]
