# Generated by Django 2.2.7 on 2019-11-08 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_escaperoom_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EscapeRoom',
            new_name='EscapeRoomSession',
        ),
    ]
